import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    chooseLanguage: "Choose your preferred language",
    continue: "Continue",
    yourApplications: "Your applications",
    noApplications: "You haven't applied to any jobs yet.",
    suggestions: "Suggestions",
    jobDescription: "Job Description",
    about: "About",
    applyNow: "Apply Now",
    save: "Save",
    saved: "Saved",
    hide: "Hide",
    experienceRequired: "Experience Required",
    salary: "Salary",
    jobType: "Job Type",
    appliedOn: "Applied on",
    selectLocation: "Select Location",
    searchLocation: "Search location...",
    filters: "Filters",
    experience: "Experience",
    clear: "Clear",
    apply: "Apply",
    searchPlaceholder: "Search jobs, skills, companies",
    welcomeToJobApp: "Welcome to Rozgar",
    getStarted: "Get Started",
    selectRole: "Select your role",
    jobSeeker: "Job Seeker",
    employer: "Employer",
    createProfile: "Create your profile",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    location: "Location",
    enterYourName: "Enter your full name",
    enterPhoneNumber: "Enter your phone number",
    enterLocation: "Enter your location",
    profileComplete: "Profile Complete!",
    startExploring: "Start Exploring",
    personalDetails: "Personal Details",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    address: "Address",
    city: "City",
    state: "State",
    pincode: "Pincode",
    next: "Next",
    back: "Back",
    skip: "Skip",
    uploadPhoto: "Upload Photo",
    education: "Education",
    skills: "Skills",
    addMore: "Add More",
    pleaseEnterValidEmail: "Please enter a valid email",
    pleaseEnterValidPhone: "Please enter a valid phone number",
    required: "Required",
    age: "Age",
    enterOtp: "Enter OTP",
    otpMessage: "We've sent an OTP to your phone number",
    didntReceive: "Didn't receive the code?",
    resend: "Resend",
    invalidOtp: "Invalid OTP. Please try again",
    whatBringsYou: "What brings you to Rozgar?",
    "jobSeeker.title": "I'm looking for work",
    "jobSeeker.description": "Find the best job opportunities near you",
    "employer.title": "I'm hiring",
    "employer.description": "Post jobs and find skilled workers",
  },
  ml: {
    chooseLanguage: "നിങ്ങളുടെ ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക",
    continue: "തുടരുക",
    yourApplications: "നിങ്ങളുടെ അപേക്ഷകൾ",
    noApplications: "നിങ്ങൾ ഇതുവരെ ജോലികൾക്ക് അപേക്ഷിച്ചിട്ടില്ല.",
    suggestions: "നിർദ്ദേശങ്ങൾ",
    jobDescription: "ജോലി വിവരണം",
    about: "കുറിച്ച്",
    applyNow: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    save: "സേവ് ചെയ്യുക",
    saved: "സേവ് ചെയ്തു",
    hide: "മറയ്ക്കുക",
    experienceRequired: "ആവശ്യമായ പരിചയം",
    salary: "ശമ്പളം",
    jobType: "ജോലി തരം",
    appliedOn: "അപേക്ഷിച്ച തീയതി",
    selectLocation: "സ്ഥലം തിരഞ്ഞെടുക്കുക",
    searchLocation: "സ്ഥലം തിരയുക...",
    filters: "ഫിൽട്ടറുകൾ",
    experience: "പരിചയം",
    clear: "മായ്ക്കുക",
    apply: "അപ്ലൈ ചെയ്യുക",
    searchPlaceholder: "ജോലികൾ, സ്കിൽസ്, കമ്പനികൾ തിരയുക",
    welcomeToJobApp: "Rozgar-ലേക്ക് സ്വാഗതം",
    getStarted: "ആരംഭിക്കുക",
    selectRole: "നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക",
    jobSeeker: "ജോലി അന്വേഷകൻ",
    employer: "തൊഴിൽദാതാവ്",
    createProfile: "നിങ്ങളുടെ പ്രൊഫൈൽ സൃഷ്ടിക്കുക",
    fullName: "മുഴുവൻ പേര്",
    phoneNumber: "ഫോൺ നമ്പർ",
    location: "സ്ഥലം",
    enterYourName: "നിങ്ങളുടെ മുഴുവൻ പേര് നൽകുക",
    enterPhoneNumber: "നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക",
    enterLocation: "നിങ്ങളുടെ സ്ഥലം നൽകുക",
    profileComplete: "പ്രൊഫൈൽ പൂർത്തിയായി!",
    startExploring: "അന്വേഷണം ആരംഭിക്കുക",
    personalDetails: "വ്യക്തിഗത വിവരങ്ങൾ",
    firstName: "പേര്",
    lastName: "അവസാന പേര്",
    email: "ഇമെയിൽ",
    address: "വിലാസം",
    city: "നഗരം",
    state: "സംസ്ഥാനം",
    pincode: "പിൻകോഡ്",
    next: "അടുത്തത്",
    back: "തിരികെ",
    skip: "സ്കിപ്പ് ചെയ്യുക",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    education: "വിദ്യാഭ്യാസം",
    skills: "കഴിവുകൾ",
    addMore: "കൂടുതൽ ചേർക്കുക",
    pleaseEnterValidEmail: "സാധുവായ ഇമെയിൽ നൽകുക",
    pleaseEnterValidPhone: "സാധുവായ ഫോൺ നമ്പർ നൽകുക",
    required: "ആവശ്യമാണ്",
    age: "വയസ്സ്",
    enterOtp: "OTP നൽകുക",
    otpMessage: "നിങ്ങളുടെ ഫോൺ നമ്പറിലേക്ക് ഞങ്ങൾ ഒരു OTP അയച്ചിട്ടുണ്ട്",
    didntReceive: "കോഡ് ലഭിച്ചില്ലേ?",
    resend: "വീണ്ടും അയയ്ക്കുക",
    invalidOtp: "തെറ്റായ OTP. വീണ്ടും ശ്രമിക്കുക",
    whatBringsYou: "Rozgar-ലേക്ക് എന്താണ് നിങ്ങളെ കൊണ്ടുവന്നത്?",
    "jobSeeker.title": "ഞാൻ ജോലി തേടുകയാണ്",
    "jobSeeker.description": "നിങ്ങൾക്ക് സമീപമുള്ള മികച്ച ജോലി അവസരങ്ങൾ കണ്ടെത്തുക",
    "employer.title": "ഞാൻ നിയമിക്കുകയാണ്",
    "employer.description": "ജോലികൾ പോസ്റ്റ് ചെയ്യുകയും വിദഗ്ധ തൊഴിലാളികളെ കണ്ടെത്തുകയും ചെയ്യുക",
  },
  hi: {
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    continue: "जारी रखें",
    yourApplications: "आपके आवेदन",
    noApplications: "आपने अभी तक किसी नौकरी के लिए आवेदन नहीं किया है।",
    suggestions: "सुझाव",
    jobDescription: "कार्य विवरण",
    about: "के बारे में",
    applyNow: "अभी आवेदन करें",
    save: "सेव करें",
    saved: "सेव किया गया",
    hide: "छिपाएं",
    experienceRequired: "आवश्यक अनुभव",
    salary: "वेतन",
    jobType: "कार्य प्रकार",
    appliedOn: "आवेदन की तिथि",
    selectLocation: "स्थान चुनें",
    searchLocation: "स्थान खोजें...",
    filters: "फ़िल्टर",
    experience: "अनुभव",
    clear: "साफ़ करें",
    apply: "लागू करें",
    searchPlaceholder: "नौकरियां, कौशल, कंपनियां खोजें",
    welcomeToJobApp: "जॉबऐप में आपका स्वागत है",
    getStarted: "शुरू करें",
    selectRole: "अपनी भूमिका चुनें",
    jobSeeker: "नौकरी खोजने वाला",
    employer: "नियोक्ता",
    createProfile: "अपनी प्रोफ़ाइल बनाएं",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    location: "स्थान",
    enterYourName: "अपना पूरा नाम दर्ज करें",
    enterPhoneNumber: "अपना फ़ोन नंबर दर्ज करें",
    enterLocation: "अपना स्थान दर्ज करें",
    profileComplete: "प्रोफ़ाइल पूर्ण!",
    startExploring: "खोजना शुरू करें",
    personalDetails: "व्यक्तिगत विवरण",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    address: "पता",
    city: "शहर",
    state: "राज्य",
    pincode: "पिन कोड",
    next: "अगला",
    back: "वापस",
    skip: "छोड़ें",
    uploadPhoto: "फोटो अपलोड करें",
    education: "शिक्षा",
    skills: "कौशल",
    addMore: "और जोड़ें",
    pleaseEnterValidEmail: "कृपया वैध ईमेल दर्ज करें",
    pleaseEnterValidPhone: "कृपया वैध फोन नंबर दर्ज करें",
    required: "आवश्यक",
    age: "आयु",
    enterOtp: "OTP दर्ज करें",
    otpMessage: "हमने आपके फोन नंबर पर एक OTP भेजा है",
    didntReceive: "कोड नहीं मिला?",
    resend: "पुनः भेजें",
    invalidOtp: "अमान्य OTP। कृपया पुनः प्रयास करें",
    whatBringsYou: "आप जॉबऐप पर क्यों आए हैं?",
    "jobSeeker.title": "मैं काम ढूंढ रहा/रही हूं",
    "jobSeeker.description": "अपने आस-पास के सर्वश्रेष्ठ रोजगार के अवसर खोजें",
    "employer.title": "मैं नियुक्ति कर रहा/रही हूं",
    "employer.description": "नौकरियां पोस्ट करें और कुशल कर्मचारी खोजें",
  },
  te: {
    chooseLanguage: "మీకు ఇష్టమైన భాష ఎంచుకోండి",
    continue: "కొనసాగించు",
    yourApplications: "మీ దరఖాస్తులు",
    noApplications: "మీరు ఇంకా ఏ ఉద్యోగానికి దరఖాస్తు చేయలేదు.",
    suggestions: "సూచనలు",
    jobDescription: "ఉద్యోగ వివరణ",
    about: "గురించి",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    save: "సేవ్ చేయండి",
    saved: "సేవ్ చేయబడింది",
    hide: "దాచు",
    experienceRequired: "అవసరమైన అనుభవం",
    salary: "జీతం",
    jobType: "ఉద్యోగ రకం",
    appliedOn: "దరఖాస్తు చేసిన తేదీ",
    selectLocation: "స్థలాన్ని ఎంచుకోండి",
    searchLocation: "స్థలాన్ని వెతకండి...",
    filters: "ఫిల్టర్లు",
    experience: "అనుభవం",
    clear: "అఴి",
    apply: "అప్లై చేయండి",
    searchPlaceholder: "ఉద్యోగాలు, నైపుణ్యాలు, కంపెనీలను హುడುకి",
    welcomeToJobApp: "జాబ్‌యాప్‌గೆ స్వాగతం",
    getStarted: "ప్రారంభించండి",
    selectRole: "మీ పాత್రను ఎంచుకోండి",
    jobSeeker: "ఉద్యోగ హುడುకುవవరು",
    employer: "యజమాని",
    createProfile: "మీ ప్రొఫైల్‌ను సృష్టించండి",
    fullName: "పూర్తి పేరు",
    phoneNumber: "ఫೋన్ సంఖ್యె",
    location: "స్థానం",
    enterYourName: "మీ పూర్తి పేరును నమోదు చేయండి",
    enterPhoneNumber: "మీ ఫೋన్ సంఖ್యెయను నమోదు చేయండి",
    enterLocation: "మీ స్థానాన్ని నమోదు చేయండి",
    profileComplete: "ప్రొఫైల్ పూర్తయింది!",
    startExploring: "అన్వేషిసలు ప్రారంభిసి",
    personalDetails: "వ్యక్తిగత వివరాలు",
    firstName: "మొదటి పేరు",
    lastName: "చివరి పేరు",
    email: "ఇమెయిల్",
    address: "చిరునామా",
    city: "నగరం",
    state: "రాష్ట్రం",
    pincode: "అఞ్చల్ కోడ్",
    next: "తదుపరి",
    back: "వెనుకకు",
    skip: "దాటవేయి",
    uploadPhoto: "ఫోటో అప್‌లోడ్ చేయండి",
    education: "విద్య",
    skills: "నైపుణ్యాలు",
    addMore: "మరిన్ని జోడించండి",
    pleaseEnterValidEmail: "దయచేసి మాన్యవాద ఇమెయిల్ నమోదు చేయండి",
    pleaseEnterValidPhone: "దయచేసి మాన్యవాద ఫೋన్ సంఖ్యెయను నమోదు చేయండి",
    required: "తప్పనిసరి",
    age: "వయసు",
    enterOtp: "OTP ని నమోదు చేయండి",
    otpMessage: "మేము మీ ఫోన్ సంఖ్యెకి OTP అంటున్నోము",
    didntReceive: "కోడ్ అందలేదా?",
    resend: "మళ్ళీ అంటున్నోము",
    invalidOtp: "చెల్లని OTP. దయచేసి మళ్ళీ ప్రయత్నించండి",
    whatBringsYou: "జాబ్‌యాప్‌కి మిమ్మల్ని ఏది తీసుకొచ్చింది?",
    "jobSeeker.title": "నేను పని కోసం చూస్తున్నాను",
    "jobSeeker.description": "మీ చుట్టుపక్కల ఉత్తమ ఉద్యోగ అవకాశాలను కనుగొనండి",
    "employer.title": "నేను నియామకం చేస్తున్నాను",
    "employer.description": "ఉద్యోగాలను పోస్ట్ చేయండి మత్తు నైపుణ్యం కలిగిన కార్మికులను కనుగొనండి",
  },
  kn: {
    chooseLanguage: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    yourApplications: "ನಿಮ್ಮ ಅರ್ಜಿಗಳು",
    noApplications: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಕೆಲಸಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿಲ್ಲ.",
    suggestions: "ಸಲಹೆಗಳು",
    jobDescription: "ಕೆಲಸದ ವಿವರಣೆ",
    about: "ಬಗ್ಗೆ",
    applyNow: "ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    save: "ಉಳಿಸಿ",
    saved: "ಉಳಿಸಲಾಗಿದೆ",
    hide: "ಮರೆಮಾಡಿ",
    experienceRequired: "ಅಗತ್ಯವಿರುವ ಅನುಭವ",
    salary: "ಸಂಬಳ",
    jobType: "ಕೆಲಸದ ಪ್ರಕಾರ",
    appliedOn: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ",
    selectLocation: "ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    searchLocation: "ಸ್ಥಳ ಹುಡುಕಿ...",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    experience: "ಅನುಭವ",
    clear: "ತೆರವುಗೊಳಿಸಿ",
    apply: "ಅನ್ವಯಿಸಿ",
    searchPlaceholder: "ಕೆಲಸಗಳು, ಕೌಶಲ್ಯಗಳು, ಕಂಪನಿಗಳನ್ನು ಹುಡುಕಿ",
    welcomeToJobApp: "ಜಾಬ್‌ಆ್ಯಪ್‌ಗೆ ಸ್ವಾಗತ",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    selectRole: "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    jobSeeker: "ಉದ್ಯೋಗ ಹುಡುಕುವವರು",
    employer: "ಉದ್ಯೋಗದಾತ",
    createProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    location: "ಸ್ಥಳ",
    enterYourName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    enterPhoneNumber: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    enterLocation: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ",
    profileComplete: "ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಂಡಿದೆ!",
    startExploring: "ಅನ್ವೇಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ",
    personalDetails: "ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
    firstName: "ಮೊದಲ ಹೆಸರು",
    lastName: "ಕೊನೆಯ ಹೆಸರು",
    email: "ಇಮೇಲ್",
    address: "ವಿಳಾಸ",
    city: "ನಗರ",
    state: "ರಾಜ್ಯ",
    pincode: "ಪಿನ್‌ಕೋಡ്",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    skip: "ಬಿಟ್ಟುಬಿಡಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    education: "ಶಿಕ್ಷಣ",
    skills: "ಕೌಶಲ್ಯಗಳು",
    addMore: "ಇನ್ನೂ ಸೇರಿಸಿ",
    pleaseEnterValidEmail: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    pleaseEnterValidPhone: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    required: "ಅಗತ್ಯವಿದೆ",
    age: "ವಯಸ್ಸು",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    otpMessage: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಗೆ ನಾವು OTP ಕಳುಹಿಸಿದ್ದೇವೆ",
    didntReceive: "ಕೋಡ್ ಸ್ವೀಕರಿಸಲಿಲ್ಲವೇ?",
    resend: "ಮರುಕಳುಹಿಸಿ",
    invalidOtp: "ಅಮಾನ್ಯ OTP. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    whatBringsYou: "ಜಾಬ್‌ಆ್ಯಪ್‌ಗೆ ನಿಮ್ಮನ್ನು ಏನು ಕರೆತರುತ್ತದೆ?",
    "jobSeeker.title": "ನಾನು ಕೆಲಸ ಹುಡುಕುತ್ತಿದ್ದೇನೆ",
    "jobSeeker.description": "ನಿಮ್ಮ ಸುತ್ತಮುತ್ತಲಿನ ಅತ್ಯುತ್ತಮ ಉದ್ಯೋಗ ಅವಕಾಶಗಳನ್ನು ಹುಡುಕಿ",
    "employer.title": "ನಾನು ನೇಮಕ ಮಾಡುತ್ತಿದ್ದೇನೆ",
    "employer.description": "ಉದ್ಯೋಗಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ ಮತ್ತು ನುರಿತ ಕಾರ್ಮಿಕರನ್ನು ಹುಡುಕಿ",
  },
  ta: {
    chooseLanguage: "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    yourApplications: "உங்கள் விண்ணப்பங்கள்",
    noApplications: "நீங்கள் இதுவரை எந்த வேலைக்கும் விண்ணப்பிக்கவில்லை.",
    suggestions: "பரிந்துரைகள்",
    jobDescription: "வேலை விவரம்",
    about: "பற்றி",
    applyNow: "இப்போதே விண்ணப்பிக்கவும்",
    save: "சேமி",
    saved: "சேமிக்கப்பட்டது",
    hide: "மறை",
    experienceRequired: "தேவையான அனுபவம்",
    salary: "சம்பளம்",
    jobType: "வேலை வகை",
    appliedOn: "விண்ணப்பித்த தேதி",
    selectLocation: "இடத்தைத் தேர்ந்தெடுக்கவும்",
    searchLocation: "இடத்தைத் தேடுங்கள்...",
    filters: "வடிப்பான்கள்",
    experience: "அனுபவம்",
    clear: "அழி",
    apply: "விண்ணப்பி",
    searchPlaceholder: "வேலைகள், திறன்கள், நிறுவனங்களைத் தேடுங்கள்",
    welcomeToJobApp: "ஜாப்ஆப்பிற்கு வரவேற்கிறோம்",
    getStarted: "தொடங்குங்கள்",
    selectRole: "உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்",
    jobSeeker: "வேலை தேடுபவர்",
    employer: "பணியமர்த்துனர்",
    createProfile: "உங்கள் சுயவிவரத்தை உருவாக்கவும்",
    fullName: "முழு பெயர்",
    phoneNumber: "தொலைபேசி எண்",
    location: "இடம்",
    enterYourName: "உங்கள் முழு பெயரை உள்ளிடவும்",
    enterPhoneNumber: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    enterLocation: "உங்கள் இடத்தை உள்ளிடவும்",
    profileComplete: "சுயவிவரம் முடிந்தது!",
    startExploring: "ஆராயத் தொடங்குங்கள்",
    personalDetails: "தனிப்பட்ட விவரங்கள்",
    firstName: "முதல் பெயர்",
    lastName: "கடைசி பெயர்",
    email: "மின்னஞ்சல்",
    address: "முகவரி",
    city: "நகரம்",
    state: "மாநிலம்",
    pincode: "அஞ்சல் குறியீடு",
    next: "அடுத்து",
    back: "பின்செல்",
    skip: "தவிர்",
    uploadPhoto: "புகைப்படத்தை பதிவேற்றவும்",
    education: "கல்வி",
    skills: "திறன்கள்",
    addMore: "மேலும் சேர்க்க",
    pleaseEnterValidEmail: "சரியான மின்னஞ்சலை உள்ளிடவும்",
    pleaseEnterValidPhone: "சரியான தொலைபேசி எண்ணை உள்ளிடவும்",
    required: "தேவை",
    age: "வயது",
    enterOtp: "OTP ஐ உள்ளிடவும்",
    otpMessage: "உங்கள் தொலைபேசி எண்ணுக்கு OTP அனுப்பியுள்ளோம்",
    didntReceive: "குறியீடு கிடைக்கவில்லையா?",
    resend: "மீண்டும் அனுப்பு",
    invalidOtp: "தவறான OTP. மீண்டும் முயற்சிக்கவும்",
    whatBringsYou: "ஜாப்ஆப்பிற்கு உங்களை எது கொண்டு வந்தது?",
    "jobSeeker.title": "நான் வேலை தேடுகிறேன்",
    "jobSeeker.description": "உங்களுக்கு அருகில் சிறந்த வேலை வாய்ப்புகளைக் கண்டறியவும்",
    "employer.title": "நான் பணியமர்த்துகிறேன்",
    "employer.description": "வேலைகளை பதிவிடவும் மற்றும் திறமையான பணியாளர்களைக் கண்டறியவும்",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Try to get the language from localStorage, default to 'en'
    return localStorage.getItem('preferredLanguage') || 'en';
  });

  useEffect(() => {
    // Save language preference whenever it changes
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 